### ISSUE TITLE
centos-systemd-etcs `supervisord.service` terminates the process

### ISSUE THREAD

**Issue by norbertpy** [Supervisor/initscripts#34]
Supervisor runs just fine if it's run manually with `sudo /usr/bin/supervisord`. But with `systemctl` and the `centos-systemd-etcs`, added as `/usr/lib/systemd/system/supervisord.service` , it runs for few seconds and it gets shut down. Relevant question I asked  on [unix.stackexchange.com][1].

 - centos 7.1
 - supervisor 3.2.0 installed with pip and easy_install

Thanks.

[1]: http://unix.stackexchange.com/questions/247995/centos-7-1-supervisord-terminates-if-run-with-systemctl

**Comment by mnaberez** [comment]
This may be fixed by 75a634ddacf60fd4b47109906131ff16bf7db5ef.  

I'm going to close this issue because as noted in the README, the Supervisor maintainers didn't write these scripts and can't provide support for them.  We are just collecting them here as a resource to try and help users.

**Comment by norbertpy** [comment]
DAMN. Thanks @mnaberez . I was stuck for two days. Thank you thank you.
